config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root 'home#index'
  get 'logout' => 'home#logout'

  get 'about' => 'home#about'
  get 'checkmywow' => 'home#checkmywow'

  resources :users, only: [:show] do
    get 'refresh'

    resources :players, only: [:index]

  end

  resources :fights, only: [:show] do
    get 'load_hp_graph'
  end

  resources :players, only: [:show] do
    collection do
      get 'search'
    end
    resources :bosses, only: [] do
      get '/:difficulty' => 'bosses#show', as: :show
    end
  end

  resources :reports, only: [:show] do

    resources :fights, only: [] do

    end
  end

  resources :zones, only: [:index] do
    collection do 
      get 'refresh'
    end
  end
  
  if Rails.env.development?
    mount Resque::Server.new, at: "/resque"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user

  def refresh
    response = HTTParty.get("https://www.warcraftlogs.com:443/v1/reports/user/#{@user_id}?api_key=#{ENV['WCL_API_KEY']}")
    case response.code
    when 500...600
      flash[:danger] = response['error']
      redirect_to :back
      return 
    when 400
      flash[:danger] = "User not found. Please try <a href='/logout'>reentering your username</a>"
      redirect_to :back
      return
    end
    reports = JSON.parse(response.body)
    reports.each do |report|
      if !Report.exists?(:report_id => report['id'])
        Report.create(
          report_id: report['id'],
          user_id: @user_id,
          title: report['title'],
          zone: report['zone'],
          started_at: Time.at(report['start']/1000),
          ended_at: Time.at(report['end']/1000),
        )
      end
    end

    redirect_to user_path(@user_id)
  end

  def show
    @reports = Report.where(user_id: @user_id).order(started_at: :desc)
  end

  private

  def get_user
    @user_id = params[:id] || params[:user_id]
    session[:user_id] = @user_id
  end
end

app/views/users/show.html.erb
<% breadcrumb :user_report, @user_id %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Logs for <%= @user_id %></h3>
    </div>
  </div>
  <%= link_to('View Reports', '', class: 'btn btn-primary') %>
  <%= link_to('View Characters', user_players_path(@user_id), class: 'btn btn-default') %>
  
  <br /><br />

  <% if @reports.size == 0 %>
    <p>Please use the "Reload Logs" button in the upper right to import your combat logs from Warcraft Logs.</p>
  <% end %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th></th>
      </tr>
    </thead>
  <% @reports.each do |report| %>
    <tr>
      <td><%= report.title %></td>
      <td><%= report.started_at.strftime("%m/%d/%Y") %></td>
      <td><%= report.imported? ? link_to('View Report', report_path(report.report_id), class: 'btn btn-primary') : '' %></td>
    </tr>
  <% end %>
  </table>
</div>