config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root 'home#index'
  get 'logout' => 'home#logout'

  get 'about' => 'home#about'
  get 'checkmywow' => 'home#checkmywow'

  resources :users, only: [:show] do
    get 'refresh'

    resources :players, only: [:index]

  end

  resources :fights, only: [:show] do
    get 'load_hp_graph'
  end

  resources :players, only: [:show] do
    collection do
      get 'search'
    end
    resources :bosses, only: [] do
      get '/:difficulty' => 'bosses#show', as: :show
    end
  end

  resources :reports, only: [:show] do

    resources :fights, only: [] do

    end
  end

  resources :zones, only: [:index] do
    collection do 
      get 'refresh'
    end
  end
  
  if Rails.env.development?
    mount Resque::Server.new, at: "/resque"
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @user_id = params[:user_id]
    @players = UserToPlayer.where(user_id: @user_id)
    @report_counts = FightParse.where(user_id: @user_id).group(:player_id).count.with_indifferent_access
  end

  def show
    @player_id = params[:id] || params[:player_id]
    @player_name = UserToPlayer.find_by(player_id: @player_id).player_name
    @zones = Zone.all.order('id DESC').includes(:bosses)
    @player_bosses = {}
    FightParse.where(player_id: @player_id).each do |fp|
      @player_bosses[fp.boss_id] = {} unless @player_bosses.has_key?(fp.boss_id)
      @player_bosses[fp.boss_id][fp.difficulty] = 0 unless @player_bosses[fp.boss_id].has_key?(fp.difficulty)
      @player_bosses[fp.boss_id][fp.difficulty] += 1
    end
  end

  def search
    @char_name = params[:char_name]
    @chars = UserToPlayer.where("player_name ILIKE ?", @char_name).to_a
    @report_counts = FightParse.where(player_id: @chars.map(&:player_id)).group(:player_id).count.with_indifferent_access
  end
end

app/views/players/index.html.erb
<% breadcrumb :user_chars, @user_id %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Logs for <%= @user_id %></h3>
    </div>
    <div class="col-md-6 text-right u-valign">
    <%= link_to('Refresh', user_refresh_path(@user_id), class: 'btn btn-info btn-lg') %>
    </div>
  </div>

  <%= link_to('View Reports', user_path(@user_id), class: 'btn btn-default') %>
  <%= link_to('View Characters', '', class: 'btn btn-primary') %>
  <br /><br />

  <% if @players.size == 0 %>
    <p>Please use the "Reload Logs" button in the upper right to import your combat logs from Warcraft Logs.</p>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>Character</th>
        <th>Parses</th>
        <th></th>
      </tr>
    </thead>
  <% @players.each do |player| %>
    <tr>
      <td><%= player.player_name %></td>
      <td><%= @report_counts[player.player_id] %></td>
      <td><%= link_to('View Reports', player_path(player.player_id), class: 'btn btn-default') %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/players/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Searching for <%= @char_name %></h3>
    </div>
  </div>

  <% if @chars.size == 0 %>
    <p>No characters found. Try again?</p>
    <%= form_tag('/players/search', method: "get") do %>
      <%= label_tag(:report_id, "Character name:") %>
      <%= text_field_tag(:char_name) %>
      <%= submit_tag("Search", class: "btn btn-primary") %>
    <% end %>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>Character</th>
        <th>Parses</th>
        <th></th>
      </tr>
    </thead>
  <% @chars.each do |player| %>
    <tr>
      <td><%= player.player_name %></td>
      <td><%= @report_counts[player.player_id] %></td>
      <td><%= link_to('View Reports', player_path(player.player_id), class: 'btn btn-default') %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/players/show.html.erb
<% breadcrumb :player, @player_id, @player_name, @user_id %>
<div class="container">
  <div class="row">
    <h3>Logs for <%= @player_name %></h3>
  </div>
  <br /><br />

  <% @zones.each do |zone| %>
    <h4><%= zone.name %></h4>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>LFR</th>
          <th>Normal</th>
          <th>Heroic</th>
          <th>Mythic</th>
        </tr>
      </thead>
      <tbody>
        <% zone.bosses.each do |boss| %>
          <% @player_bosses[boss.id] ||= {} %>
          <tr>
            <td><%= boss.name %></td>
            <% [1,3,4,5].each do |difficulty| # ignore flex %> 
              <td>
                <% @player_bosses[boss.id][difficulty] ||= 0 %>
                <%= link_to("Compare #{@player_bosses[boss.id][difficulty]}", player_boss_show_path(@player_id, boss.id, difficulty), class: 'btn btn-default') if @player_bosses[boss.id][difficulty] > 0 %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>