config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root 'home#index'
  get 'logout' => 'home#logout'

  get 'about' => 'home#about'
  get 'checkmywow' => 'home#checkmywow'

  resources :users, only: [:show] do
    get 'refresh'

    resources :players, only: [:index]

  end

  resources :fights, only: [:show] do
    get 'load_hp_graph'
  end

  resources :players, only: [:show] do
    collection do
      get 'search'
    end
    resources :bosses, only: [] do
      get '/:difficulty' => 'bosses#show', as: :show
    end
  end

  resources :reports, only: [:show] do

    resources :fights, only: [] do

    end
  end

  resources :zones, only: [:index] do
    collection do 
      get 'refresh'
    end
  end
  
  if Rails.env.development?
    mount Resque::Server.new, at: "/resque"
  end

end

app/controllers/bosses_controller.rb
class BossesController < ApplicationController
  def show
    @player_id = params[:player_id]
    @player_name = UserToPlayer.find_by(player_id: @player_id).player_name
    @boss_id = params[:boss_id].to_i
    @difficulty = params[:difficulty].to_i
    @boss_name = Boss.find(@boss_id).name

    @fights = FightParse.where(player_id: @player_id, boss_id: @boss_id, difficulty: @difficulty).order(report_started_at: :desc)

    case params[:tab]
    when 'resources'
      render template: 'bosses/show_resources'
    when 'cooldowns'
      @max_gps = 0
      @max_ebps = 0
      @max_dhps = 0
      @max_dmps = 0
      @max_zmps = 0
      @max_fbps = 0
      @fights.each do |f|
        @max_gps = f.gps if f.gps > @max_gps
        @max_ebps = f.ebps if f.ebps > @max_ebps
        @max_dhps = (f.dh_reduced / f.fight_time) if (f.dh_reduced / f.fight_time) > @max_dhps
        @max_dmps = (f.dm_reduced / f.fight_time) if (f.dm_reduced / f.fight_time) > @max_dmps
        @max_zmps = (f.zm_reduced / f.fight_time) if (f.zm_reduced / f.fight_time) > @max_zmps
        @max_fbps = (f.fb_reduced / f.fight_time) if (f.fb_reduced / f.fight_time) > @max_fbps
      end
      render template: 'bosses/show_cooldowns'
    else
      @max_dps = 0
      @max_dtps = 0
      @max_shps = 0
      @max_ehps = 0
      @fights.each do |f|
        @max_dps = f.dps if f.dps > @max_dps
        @max_dtps = f.dtps if f.dtps > @max_dtps
        @max_shps = f.shps if f.shps > @max_shps
        @max_ehps = f.ehps if f.ehps > @max_ehps
      end
      render template: 'bosses/show_basic'
    end
  end
end

app/views/bosses/show.html.erb
<div class="container">
  <h5><small><%= link_to @player_name, player_path(@player_id) %>&nbsp;&nbsp;>&nbsp;&nbsp;</small><%= "#{@boss_name}" %></h5>

  <%= link_to('Key Metrics', '?tab=basic', class: 'button button-primary') %>
  <%= link_to('Resource Management', '?tab=resources', class: 'button') %>
  <%= link_to('Cooldown Usage', '?tab=cooldowns', class: 'button') %>
  <br /><br />
  <section>
    <h4>Damage per Second</h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="one column"><%= link_to fp.fight_date, fight_path(fp.fight_id) %></div>
        <div class="five columns">
          <div class="bar light" style="width: <%= 100 * fp.dps / @max_dps %>%">
            <div class="bar" style="width: <%= 100 * fp.player_damage_done / (fp.player_damage_done + fp.pet_damage_done) %>%"><%= fp.dps %></div>
          </div>
        </div>
        <div class="six columns"><%= fp.player_damage_done / 1000 %>k total damage (<%= fp.pet_damage_done / 1000 %>k pet)</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>Damage Taken per Second</h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="one column"><%= link_to fp.fight_date, fight_path(fp.fight_id) %></div>
        <div class="five columns">
          <div class="bar" style="width: <%= 100 * fp.dtps / @max_dtps %>%">
            <%= fp.dtps %>
          </div>
        </div>
        <div class="six columns"><%= fp.damage_taken / 1000 %>k total damage taken</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>Self Healing per Second</h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="one column"><%= link_to fp.fight_date, fight_path(fp.fight_id) %></div>
        <div class="five columns">
          <div class="bar light" style="width: <%= 100 * fp.shps / @max_shps %>%">
            <div class="bar" style="width: <%= 100 * fp.self_healing / (fp.self_healing + fp.self_absorbing) %>%">
              <%= fp.shps %>
            </div>
          </div>
        </div>
        <div class="six columns"><%= fp.self_healing / 1000 %>k healed, <%= fp.self_absorbing / 1000 %>k absorbed</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>External Healing per Second</h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="one column"><%= link_to fp.fight_date, fight_path(fp.fight_id) %></div>
        <div class="five columns">
          <div class="bar light" style="width: <%= 100 * fp.ehps / @max_ehps %>%">
            <div class="bar" style="width: <%= 100 * fp.external_healing / (fp.external_healing + fp.external_absorbing) %>%">
              <%= fp.ehps %>
            </div>
          </div>
        </div>
        <div class="six columns"><%= fp.external_healing / 1000 %>k healed, <%= fp.external_absorbing / 1000 %>k absorbed</div>
      </div>
    <% end %>
  </section>
</div>

app/views/bosses/show_basic.html.erb
<% breadcrumb :boss, @boss_id, @boss_name, @difficulty, @player_id, @player_name %>
<div class="container">
  <h3><%= "#{@boss_name} (#{DifficultyType.label(@difficulty)}) - Comparison" %></h3>

  <%= link_to('Key Metrics', '?tab=basic', class: 'btn btn-primary') %>
  <%= link_to('Resource Management', '?tab=resources', class: 'btn btn-default') %>
  <%= link_to('Cooldown Usage', '?tab=cooldowns', class: 'btn btn-default') %>
  <br /><br />
  <section>
    <h4>Damage per Second <a class="tiny" data-toggle="popover" title="Damage per Second" data-content="Total damage / Fight time. Xuen's damage is shown with a separate color">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
          <div class="bar light" style="width: <%= 100 * fp.dps / @max_dps %>%">
            <div class="bar" style="width: <%= 100 * fp.player_damage_done / (fp.player_damage_done + fp.pet_damage_done) %>%"><%= fp.dps %>/s</div>
          </div>
        </div>
        <div class="col-md-6"><%= (fp.player_damage_done + fp.pet_damage_done) / 1000 %>k total damage (<%= fp.pet_damage_done / 1000 %>k pet)</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>Damage Taken per Second <a class="tiny" data-toggle="popover" title="Damage Taken per Second" data-content="This is the total damage (divided by fight time) that actually reduced your HP. Absorbs are not included.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
          <div class="bar" style="width: <%= 100 * fp.dtps / @max_dtps %>%">
            <%= fp.dtps %>/s
          </div>
        </div>
        <div class="col-md-6"><%= fp.damage_taken / 1000 %>k total damage taken</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>Self Healing per Second <a class="tiny" data-toggle="popover" title="Self Healing per Second" data-content="The total amount (divided by fight time) that you healed yourself. Absorbs are shown with a separate color.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
          <div class="bar light" style="width: <%= 100 * fp.shps / @max_shps %>%">
            <div class="bar" style="width: <%= 100 * fp.self_healing / (fp.self_healing + fp.self_absorbing) %>%">
              <%= fp.shps %>/s
            </div>
          </div>
        </div>
        <div class="col-md-6"><%= fp.self_healing / 1000 %>k healed, <%= fp.self_absorbing / 1000 %>k absorbed</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>External Healing per Second <a class="tiny" data-toggle="popover" title="External Healing per Second" data-content="The total amount (divided by fight time) that other sources healed you. Absorbs are shown with a separate color.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
          <div class="bar light" style="width: <%= 100 * fp.ehps / @max_ehps %>%">
            <div class="bar" style="width: <%= 100 * fp.external_healing / (fp.external_healing + fp.external_absorbing) %>%">
              <%= fp.ehps %>/s
            </div>
          </div>
        </div>
        <div class="col-md-6"><%= fp.external_healing / 1000 %>k healed, <%= fp.external_absorbing / 1000 %>k absorbed</div>
      </div>
    <% end %>
  </section>
</div>

<script>
$(function () {
  $('[data-toggle="popover"]').popover();
})
</script>

app/views/bosses/show_cooldowns.html.erb
<% breadcrumb :boss, @boss_id, @boss_name, @difficulty, @player_id, @player_name %>
<div class="container">
  <h3><%= "#{@boss_name} (#{DifficultyType.label(@difficulty)}) - Comparison" %></h3>

  <%= link_to('Key Metrics', '?tab=basic', class: 'btn btn-default') %>
  <%= link_to('Resource Management', '?tab=resources', class: 'btn btn-default') %>
  <%= link_to('Cooldown Usage', '?tab=cooldowns', class: 'btn btn-primary') %>
  <br /><br />
  <section>
    <h4>Guard Effectiveness <a class="tiny" data-toggle="popover" title="Guard Effectiveness" data-content="The total amount of damage mitigated through Guard / fight time. The effectiveness of each invididual Guard cast is the sum of the damage that was absorbed (light color), and the 30% boost to self-healing (dark color).">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
      <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
      <div class="col-md-5">
        <div class="bar light" style="width: <%= 100 * fp.gps / @max_gps rescue 0 %>%">
          <div class="bar" style="width: <%= 100 * fp.guard_healed / (fp.guard_absorbed + fp.guard_healed) rescue 0 %>%"><%= fp.gps %>/s</div>
        </div>
      </div>
      <div class="col-md-3"><%= fp.guard_healed / 1000 %>k healed, <%= fp.guard_absorbed / 1000 %>k absorbed</div>
    </div>
    <% end %>
  </section>

  <section>
    <h4>Elusive Brew Effectiveness <a class="tiny" data-toggle="popover" title="Elusive Brew Effectiveness" data-content="The total amount of damage mitigated through Elusive Brew / fight time. The effectiveness of each invididual Elusive Brew cast is calculated by recording each attack that was dodged, and summing the damage it would have done had it hit you, based on average damage taken from that ability over the course of the fight.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
      <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
      <div class="col-md-5">
          <div class="bar" style="width: <%= 100 * fp.ebps / @max_ebps rescue 0 %>%">
            <%= fp.ebps %>/s
          </div>
      </div>
      <div class="col-md-3"><%= fp.eb_avoided / 1000 %>k avoided</div>
    </div>
    <% end %>
  </section>

  <% if @max_dhps > 0 %>
    <section>
      <h4>Dampen Harm Effectiveness <a class="tiny" data-toggle="popover" title="Dampen Harm Effectiveness" data-content="The total amount of damage mitigated through Dampen Harm / fight time. Each cast of Dampen Harm has its 3 highest hitting attacks recorded, and calculates the total damage mitigation (50% if the attack did >15% of your total health). Because the mitigation happens before any damage is recorded, it's difficult to know for sure whether an attack that did between 7.5-15% of your total health was actually mitigated or not.">Explain this</a></h4>
      <% @fights.each do |fp| %>
        <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
            <div class="bar" style="width: <%= 100 * (fp.dh_reduced / fp.fight_time) / @max_dhps rescue 0  %>%">
              <%= fp.dh_reduced / fp.fight_time %>/s
            </div>
        </div>
        <div class="col-md-3"><%= fp.dh_reduced / 1000 %>k avoided</div>
      </div>
      <% end %>
    </section>
  <% end %>
  <% if @max_dmps > 0 %>
    <section>
      <h4>Diffuse Magic Effectiveness <a class="tiny" data-toggle="popover" title="Diffuse Magic Effectiveness" data-content="The total amount of damage mitigated through Diffuse magic / fight time. Each cast of Diffuse Magic records all magic damage taken while it is up, and calculates the total mitigation (90%)">Explain this</a></h4>
      <% @fights.each do |fp| %>
        <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
            <div class="bar" style="width: <%= 100 * (fp.dm_reduced / fp.fight_time) / @max_dmps rescue 0  %>%">
              <%= fp.dm_reduced / fp.fight_time %>/s
            </div>
        </div>
        <div class="col-md-3"><%= fp.dm_reduced / 1000 %>k avoided</div>
      </div>
      <% end %>
    </section>
  <% end %>
  <% if @max_zmps > 0 %>
    <section>
      <h4>Zen Meditation Effectiveness <a class="tiny" data-toggle="popover" title="Zen Meditation Effectiveness" data-content="The total amount of damage mitigated through Zen Meditation / fight time. Each cast of Zen Meditation records all damage taken while it is up, and calculates the total mitigation (90%)">Explain this</a></h4>
      <% @fights.each do |fp| %>
        <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
            <div class="bar" style="width: <%= 100 * (fp.zm_reduced / fp.fight_time) / @max_zmps rescue 0  %>%">
              <%= fp.zm_reduced / fp.fight_time %>/s
            </div>
        </div>
        <div class="col-md-3"><%= fp.zm_reduced / 1000 %>k avoided</div>
      </div>
      <% end %>
    </section>
  <% end %>
  <% if @max_fbps > 0 %>
    <section>
      <h4>Fortifying Brew Effectiveness <a class="tiny" data-toggle="popover" title="Fortifying Brew Effectiveness" data-content="The total amount of damage mitigated through Fortifying Brew / fight time. Each cast of Fortifying Brew records all damage taken while it is up, and calculates the total mitigation (20%). Increased Stagger is not taken into effect here, so its total effectiveness may be understated.">Explain this</a></h4>
      <% @fights.each do |fp| %>
        <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
            <div class="bar" style="width: <%= 100 * (fp.fb_reduced / fp.fight_time) / @max_fbps rescue 0  %>%">
              <%= fp.fb_reduced / fp.fight_time %>/s
            </div>
        </div>
        <div class="col-md-3"><%= fp.fb_reduced / 1000 %>k avoided</div>
      </div>
      <% end %>
    </section>
  <% end %>
</div>

<script>
$(function () {
  $('[data-toggle="popover"]').popover();
})
</script>

app/views/bosses/show_resources.html.erb
<% breadcrumb :boss, @boss_id, @boss_name, @difficulty, @player_id, @player_name %>
<div class="container">
  <h3><%= "#{@boss_name} (#{DifficultyType.label(@difficulty)}) - Comparison" %></h3>

  <%= link_to('Key Metrics', '?tab=basic', class: 'btn btn-default') %>
  <%= link_to('Resource Management', '?tab=resources', class: 'btn btn-primary') %>
  <%= link_to('Cooldown Usage', '?tab=cooldowns', class: 'btn btn-default') %>
  <br /><br />
  <section>
    <h4>Kegsmash Efficiency <a class="tiny" data-toggle="popover" title="Kegsmash Efficiency" data-content="The number of times you cast Kegsmash / the number of casts you had time for. Aim for 100%.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
          <div class="bar white" style="width: 100%">
            <div class="bar" style="width: <%= 800 * fp.kegsmash / fp.fight_time %>%"><%= fp.kegsmash %></div>
          </div>
        </div>
        <div class="col-md-3"><%= fp.kegsmash %> / <%= fp.fight_time / 8 %> (<%= 800 * fp.kegsmash / fp.fight_time %>%)</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>Tigerpalm Casts <a class="tiny" data-toggle="popover" title="Tigerpalm Casts" data-content="It's hard to say how many Tigerpalm casts is 'good', but this should be high since you can cast it every GCD that you're not doing something else.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
            <div class="bar" style="width: <%= [200 * fp.tigerpalm / fp.fight_time, 100].min %>%"><%= fp.tigerpalm %></div>
        </div>
        <div class="col-md-3"><%= (1.0 * fp.tigerpalm / fp.fight_time).round(2) %> casts/s</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>Shuffle Uptime <a class="tiny" data-toggle="popover" title="Shuffle Uptime" data-content="The percent of the fight that you had Shuffle active. Aim for 100%.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
          <div class="bar white" style="width: 100%">
            <div class="bar" style="width: <%= fp.shuffle / (10 * fp.fight_time) %>%">
              <%= fp.shuffle / (10 * fp.fight_time) %>%
            </div>
          </div>
        </div>
        <div class="col-md-3"><%= fp.shuffle / 1000 %>s / <%= fp.fight_time %>s</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>Time not Energy-Capped <a class="tiny" data-toggle="popover" title="Time not Energy-Capped" data-content="The percent of the fight that you had less than max Energy (expect while Serenity was active). Aim for 100%.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
          <div class="bar white" style="width: 100%">
            <div class="bar" style="width: <%= 100*(fp.fight_time - fp.capped_time) / fp.fight_time %>%">
              <%= fp.fight_time - fp.capped_time %>s
            </div>
          </div>
        </div>
        <div class="col-md-3"><%= fp.fight_time - fp.capped_time %>s / <%= fp.fight_time %>s</div>
      </div>
    <% end %>
  </section>

  <section>
    <h4>Stagger Purified <a class="tiny" data-toggle="popover" title="Stagger Purified" data-content="The amount of Stagger purified / the total amount of damage converted to Stagger. 100% is unrealistic, but higher percents mean you take less damage.">Explain this</a></h4>
    <% @fights.each do |fp| %>
      <div class="row">
        <div class="col-md-1"><%= link_to fp.fight_date, fight_path(fp.fight_hash) %></div>
        <div class="col-md-5">
          <div class="bar white" style="width: 100%">
            <div class="bar" style="width: <%= 100 * (fp.damage_to_stagger - fp.damage_from_stagger) / fp.damage_to_stagger %>%">
              <%= 100 * (fp.damage_to_stagger - fp.damage_from_stagger) / fp.damage_to_stagger %>%
            </div>
          </div>
        </div>
        <div class="col-md-3"><%= (fp.damage_to_stagger - fp.damage_from_stagger) / 1000 %>k / <%= fp.damage_to_stagger / 1000 %>k</div>
      </div>
    <% end %>
  </section>
</div>

<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>