config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root 'home#index'
  get 'logout' => 'home#logout'

  get 'about' => 'home#about'
  get 'checkmywow' => 'home#checkmywow'

  resources :users, only: [:show] do
    get 'refresh'

    resources :players, only: [:index]

  end

  resources :fights, only: [:show] do
    get 'load_hp_graph'
  end

  resources :players, only: [:show] do
    collection do
      get 'search'
    end
    resources :bosses, only: [] do
      get '/:difficulty' => 'bosses#show', as: :show
    end
  end

  resources :reports, only: [:show] do

    resources :fights, only: [] do

    end
  end

  resources :zones, only: [:index] do
    collection do 
      get 'refresh'
    end
  end
  
  if Rails.env.development?
    mount Resque::Server.new, at: "/resque"
  end

end

app/views/layouts/_footer.html.erb
<div id="footer">
 <p>Fork me on <a href="https://github.com/aonsager/bmlogs" target="_blank">Github</a>&nbsp;&nbsp;|&nbsp;&nbsp;Reach me on twitter: <a href="http://twitter.com/epwna_monk" target="_blank">@epwna_monk</a></p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Brewmaster Logs", logout_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= breadcrumbs style: :bootstrap, autoroot: false, display_single_fragment: true %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if session.has_key?(:user_id) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= session[:user_id] %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "View Reports", user_path(session[:user_id]) %></li>
              <li><%= link_to "View Characters", user_players_path(session[:user_id]) %></li>
              <li class="divider"></li>
              <li><a href="#"><%= link_to "Change User", logout_path %></a></li>
            </ul>
          </li>
        <% end %>
        <% if session.has_key?(:char_id) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= session[:char_id] %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "View Reports", user_path(session[:char_id]) %></li>
              <li class="divider"></li>
              <li><a href="#"><%= link_to "Change Character", logout_path %></a></li>
            </ul>
          </li>
        <% end %>
        <li><%= link_to "About this site", about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brewmaster Logs</title>
  <!--  CSS  -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--  SCRIPT  -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--  META  -->
  <%= csrf_meta_tags %>
  <meta name="description" content="A site for Brewmasters in the World of Warcraft who want to improve by tracking their performance across raid encounters, based on a small number of key metrics.">
</head>
<body>
  <div id="wrapper">
    <%= render "layouts/header" %>
    <div class="notif">
      This site is moving to <a href="http://www.checkmywow.com">www.checkmywow.com</a>. Please read more <a href="/checkmywow">here</a>.
    </div>
    <% flash.each do |type, msg| -%>
      <div class="alert alert-<%=type%> alert-dismissible">
        <%=raw msg %>
      </div>
      <% end -%>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65668017-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>